language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install: true
script: "./mvnw --batch-mode --errors --update-snapshots clean install"
deploy:
  provider: script
  script: sh .travis-support/deploy.sh
  on:
    branch: master
env:
  global:
